/**
 * Regenerates the third-party files under vendor/ from npm packages.
 *
 * Manifest V3 forbids loading remote code, so everything the extension runs
 * ships in the repository. Rerun after upgrading any of these packages and
 * commit the result.
 *
 * - vendor/highlight.js: highlight.js core plus the grammars that
 *   detectCodeLanguage (src/converter.js) can return, as one classic script.
 * - vendor/tesseract/: Tesseract.js for OCR (main script, worker, the SIMD
 *   LSTM core and the English model), loaded by src/offscreen.html.
 *
 * Usage: npm run vendor
 */
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VENDOR = path.join(ROOT, "vendor");
const HIGHLIGHT_LANGUAGES = ["cpp", "bash", "makefile"];

const require = createRequire(import.meta.url);
const packageDir = (name, from = require) => path.dirname(from.resolve(`${name}/package.json`));
const versionOf = async (dir) => JSON.parse(await readFile(path.join(dir, "package.json"), "utf8")).version;

async function buildHighlight() {
  const dir = packageDir("highlight.js");
  const version = await versionOf(dir);
  const entry = `
import hljs from "highlight.js/lib/core";
${HIGHLIGHT_LANGUAGES.map((name) => `import ${name} from "highlight.js/lib/languages/${name}";`).join("\n")}
${HIGHLIGHT_LANGUAGES.map((name) => `hljs.registerLanguage("${name}", ${name});`).join("\n")}

/** Returns highlighted HTML (input is escaped by highlight.js). */
export function highlight(code, language) {
  return hljs.highlight(code, { language, ignoreIllegals: true }).value;
}
`;
  await build({
    stdin: { contents: entry, resolveDir: ROOT, loader: "js" },
    bundle: true,
    minify: true,
    format: "iife",
    globalName: "Ics45cHighlight",
    legalComments: "inline",
    banner: {
      js: `/* Generated by scripts/vendor.mjs from highlight.js ${version} (${HIGHLIGHT_LANGUAGES.join(", ")}). Do not edit. BSD-3-Clause, see highlight.js.LICENSE. */`,
    },
    outfile: path.join(VENDOR, "highlight.js"),
  });
  await copyFile(path.join(dir, "LICENSE"), path.join(VENDOR, "highlight.js.LICENSE"));
  console.log(`vendor/highlight.js: highlight.js ${version}`);
}

/** Copies a minified script without its sourceMappingURL (the maps are not shipped). */
async function copyScript(from, to) {
  const source = await readFile(from, "utf8");
  await writeFile(to, source.replace(/\n?\/\/# sourceMappingURL=\S+\s*$/, "\n"));
}

async function vendorTesseract() {
  const out = path.join(VENDOR, "tesseract");
  await rm(out, { recursive: true, force: true });
  await mkdir(path.join(out, "lang"), { recursive: true });

  // Tesseract.js pins its own core version, so resolve the core through it.
  const main = packageDir("tesseract.js");
  const core = packageDir("tesseract.js-core", createRequire(path.join(main, "package.json")));
  const data = packageDir("@tesseract.js-data/eng");

  for (const file of ["tesseract.min.js", "worker.min.js"]) {
    await copyScript(path.join(main, "dist", file), path.join(out, file));
    await copyFile(path.join(main, "dist", `${file}.LICENSE.txt`), path.join(out, `${file}.LICENSE.txt`));
  }
  // Every Chromium the extension supports has WebAssembly SIMD.
  await copyScript(path.join(core, "tesseract-core-simd-lstm.js"), path.join(out, "tesseract-core-simd-lstm.js"));
  await copyFile(path.join(core, "tesseract-core-simd-lstm.wasm"), path.join(out, "tesseract-core-simd-lstm.wasm"));
  await copyFile(path.join(data, "4.0.0_best_int", "eng.traineddata.gz"), path.join(out, "lang", "eng.traineddata.gz"));
  await copyFile(path.join(main, "LICENSE.md"), path.join(out, "LICENSE-tesseract.js.md"));
  await copyFile(path.join(core, "LICENSE"), path.join(out, "LICENSE-tesseract.js-core"));

  const [mainVersion, coreVersion, dataVersion] = await Promise.all([versionOf(main), versionOf(core), versionOf(data)]);
  await writeFile(
    path.join(out, "README.md"),
    `# Vendored Tesseract.js

Generated by \`scripts/vendor.mjs\`; do not edit.

| File | Source | License |
| --- | --- | --- |
| \`tesseract.min.js\`, \`worker.min.js\` | tesseract.js ${mainVersion} | Apache-2.0 |
| \`tesseract-core-simd-lstm.*\` | tesseract.js-core ${coreVersion} | Apache-2.0 |
| \`lang/eng.traineddata.gz\` | @tesseract.js-data/eng ${dataVersion} (\`4.0.0_best_int\`, from tesseract-ocr/tessdata) | Apache-2.0 |
`,
  );
  console.log(`vendor/tesseract: tesseract.js ${mainVersion}, core ${coreVersion}, eng data ${dataVersion}`);
}

await buildHighlight();
await vendorTesseract();
